cc_library(
    name = "main_2d",
    srcs = [
        "contour_2d.cpp",
        "edge_detection_2d.cpp",
    ],
    hdrs = [
        "contour_2d.h",
        "edge_detection_2d.h",
    ],
    deps = [
        "//base/geometrics:geometrics",
        "@pcl//:common",
        "//:opencv",
    ],
    visibility = ["//visibility:public"],
)
