cc_library(
    name = "geometrics",
    srcs = [
        "line_3d.cpp",
        "point_cloud.cpp",
        "quadtree.cpp",
    ],
    hdrs = [
        "line_3d.h",
        "point_cloud.h",
        "quadtree.h",
    ],
    deps = [
        "//base/misc:misc",
        "//base:base",
        "@pcl//:common",
        "@pcl//:filters",
        "@pcl//:io",
    ],
    visibility = ["//visibility:public"],
)
