cc_library(
    name = "misc",
    srcs = [
        "color.cpp",
        "histogram.cpp",
        "math_statistics.cpp",
    ],
    hdrs = [
        "color.h",
        "histogram.h",
        "math_statistics.h",
    ],
    visibility = ["//visibility:public"],
)
